stages:
  - build
  - test
  - deploy

build-app:
  stage: build
  script:
    - npm i
    - npm run build:coverage

playwright:
  stage: test
  allow_failure: true
  script:
    - npx playwright test --project=ts-etl-ui

check-coverage:
  stage: test
  allow_failure: true
  script:
    - npx nyc report

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
