name: Deployment to Render

on:
  push:
    branches:
      - master

jobs:
  trigger_deploy_to_render:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Trigger auto deploy to render on PR merge
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
            service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api-key: ${{ secrets.MY_RENDER_API_KEY }}
            wait-for-success: true