name: Playwright Tests
on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e-test:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    name: e2e-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Output Node Version
        run: node -v

      - name: Output NPM Version
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Grant git permission
        run: git config --global --add safe.directory /__w/ts-etl-ui/ts-etl-ui

      - name: Build Angular
        run: npm run build

      - name: Start Node Server - in background
        run: npm run start &

      - name: Run Playwright tests
        run: PR=${{ github.event.number }} npm run test

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload playwright report to github-pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

      - name: Deploy Playwright result to Github Pages
        if: always()
        id: deploy-playwright-to-github
        uses: actions/deploy-pages@v4

      - name: update job summary
        if: always()
        run: echo "# Deployed playwright result to ${{ steps.deploy-playwright-to-github.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY