name: Playwright Tests
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e-test:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    name: e2e-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Output Node Version
        run: node -v

      - name: Output NPM Version
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Grant git permission
        run: git config --global --add safe.directory /__w/ts-etl-ui/ts-etl-ui

      - name: Build Angular
        run: npm run build:ci

      - name: Reset MongoDb
        run: PR=${{ github.event.number }} node --env-file .ci.env reset-mongo-db.js

      - name: Run Playwright tests
        run: PR=${{ github.event.number }} npm run test

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload playwright report to github-pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

      - name: Deploy Playwright result to Github Pages
        if: always()
        id: deploy-playwright-to-github
        uses: actions/deploy-pages@v4

      - name: update job summary
        if: always()
        run: echo "# Deployed playwright result to ${{ steps.deploy-playwright-to-github.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY

      - name: Setup JDK
        uses: actions/setup-java@3

      - name: Download allure report from previous run
        run: echo 'Download allure report from previous run'

      - name: Copy historical data into current run
        run: echo 'copy {previous run history folder} .allure-results

      - name: Generate allure report
        run: npx allure generate allure-results

      - name: Upload allure report to Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 30