name: Playwright Tests
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GH_TOKEN: ${{ secrets.GithubCliToken }}

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Grant git permission
        run: git config --global --add safe.directory /__w/ts-etl-ui/ts-etl-ui

      - name: Build Angular
        run: npm run build:ci

      - name: Reset MongoDb
        run: PR=${{ github.event.number }} node --env-file server/.ci.env server/reset-mongo-db.js

      - name: Run Playwright tests
        run: PR=${{ github.event.number }} npm run test

      - name: Generate coverage report
        run: npm run coverage-report

      - name: Merge both playwright & coverage report
        run: mv playwright-report coverage-e2e all-report

      - name: Upload playwright report to artifact named github-pages # the next step's action expect this exactly artifact name
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: all-report

      - name: Deploy playwright report to Github Pages
        if: always()
        id: deploy-playwright-report-to-github-page
        uses: actions/deploy-pages@v4
        with:
          preview: true

      - name: update job summary
        if: always()
        run: echo "# Deployed playwright report to ${{ steps.deploy-playwright-report-to-github-page.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
