name: Playwright Tests
on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Output Node Version
        run: node -v

      - name: Output NPM Version
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Grant git permission
        run: git config --global --add safe.directory /__w/ts-etl-ui/ts-etl-ui

      - name: Build Angular
        run: npm run build

      - name: Run Playwright tests
        run: PR=${{ github.event.number }} MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} npm run test

      - name: Upload playwright report to Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
